name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      archipelago:
        image: quay.io/airbreather/archipelagomw-server:20260414
        ports:
          - 38281:38281

    steps:
      - uses: actions/checkout@v6

      - name: Get Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run Tests
        run: bun test --coverage
