name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
            node-version: '24'

      - name: Install dependencies
        run: pnpm install

      - name: Run All Tests
        id: try_full
        timeout-minutes: 5 # takes less than 1m on my machine, virtually all of which is in nix-build
        run: |
          build=test/integration/smoke-test/generate.nix
          log=test/integration/server-logs/smoke.txt
          zip=AP_77736814537648744499.zip
          nix-shell \
            -p archipelago \
            --run "archipelago MultiServer -- $(nix-build $build --no-out-link)/$zip" '<nixpkgs>' >$log &
          while ! grep -i 'listening on .*:38281$' $log 2>/dev/null; do sleep 0.1; done
          pnpm run full-test:coverage

      - name: Run Only Non-Integration Tests
        if: (!cancelled() && steps.try_full.outcome != 'success')
        run: pnpm run test:coverage

      - name: 'Report Coverage'
        if: (!cancelled())
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: 'all'
